
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Bai22 extends javax.swing.JFrame {

    /**
     * Creates new form Bai22
     */
    public Bai22() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        txtNhapChuoi = new javax.swing.JTextField();
        txtNoiDungFile = new javax.swing.JTextField();
        btDocFileNhiPhan = new javax.swing.JButton();
        btVietFileNhiPhan = new javax.swing.JButton();
        btDocFileVanBan = new javax.swing.JButton();
        btVietFileVanBan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập Tên Tập Tin: ");

        jLabel2.setText("Nhập Chuỗi : ");

        jLabel3.setText("Nội Dung File");

        txtFileName.setText("C:\\");

            btDocFileNhiPhan.setText("Đọc File Nhị Phân");
            btDocFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDocFileNhiPhanActionPerformed(evt);
                }
            });

            btVietFileNhiPhan.setText("Ghi File Nhị Phân");
            btVietFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btVietFileNhiPhanActionPerformed(evt);
                }
            });

            btDocFileVanBan.setText("Đọc File Văn Bản");
            btDocFileVanBan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDocFileVanBanActionPerformed(evt);
                }
            });

            btVietFileVanBan.setText("Ghi File Văn Bản");
            btVietFileVanBan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btVietFileVanBanActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(txtNhapChuoi)
                                .addComponent(txtNoiDungFile)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btDocFileVanBan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btVietFileVanBan))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btDocFileNhiPhan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                    .addComponent(btVietFileNhiPhan)))))
                    .addContainerGap(97, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addComponent(jLabel2))
                        .addComponent(txtNhapChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(txtNoiDungFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btDocFileNhiPhan)
                        .addComponent(btVietFileNhiPhan))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btDocFileVanBan)
                        .addComponent(btVietFileVanBan))
                    .addContainerGap(36, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btDocFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocFileNhiPhanActionPerformed
        // TODO add your handling code here:
        byte a[]=new byte[20];
        File file;
        try{
            file=new File(txtFileName.getText());
            FileInputStream fi=new FileInputStream(file);
            a=new byte[fi.available()];
            fi.read(a);
            fi.close();
            txtNoiDungFile.setText(new String(a));
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btDocFileNhiPhanActionPerformed

    private void btVietFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVietFileNhiPhanActionPerformed
        // TODO add your handling code here:
        byte a[]=new byte[20];
       File file;
       int i;
       char s[]= txtNhapChuoi.getText().toCharArray();
       for(i=0; i<s.length; i++){
           a[i]=(byte) s[i];
       }
       try{
           file=new File(txtFileName.getText());
           FileOutputStream fo=new FileOutputStream(file);
           fo.write(a);
           fo.close();
       }catch(IOException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_btVietFileNhiPhanActionPerformed

    private void btDocFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocFileVanBanActionPerformed
        // TODO add your handling code here:
        try{
           FileReader fr=new FileReader(new File(txtFileName.getText()));
           StringBuffer sb=new StringBuffer();
           char ca[]=new char[5];
           while(fr.ready()){
               int len=fr.read(ca);
               sb.append(ca,0,len);
           }
           fr.close();
           txtNoiDungFile.setText(sb+"");
       }catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_btDocFileVanBanActionPerformed

    private void btVietFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVietFileVanBanActionPerformed
        // TODO add your handling code here:
        try{
           FileWriter fw=new FileWriter(new File(txtFileName.getText()));
           fw.write(txtNhapChuoi.getText());
           fw.close();
       }catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_btVietFileVanBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDocFileNhiPhan;
    private javax.swing.JButton btDocFileVanBan;
    private javax.swing.JButton btVietFileNhiPhan;
    private javax.swing.JButton btVietFileVanBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtNhapChuoi;
    private javax.swing.JTextField txtNoiDungFile;
    // End of variables declaration//GEN-END:variables
}
