/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Administrator
 */
public class B3_TH7 extends javax.swing.JFrame {

    /**
     * Creates new form IP
     */
    public B3_TH7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_so1 = new javax.swing.JTextField();
        txt_so2 = new javax.swing.JTextField();
        txt_so3 = new javax.swing.JTextField();
        txt_so4 = new javax.swing.JTextField();
        txt_subnet = new javax.swing.JTextField();
        btn_Tinh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JTextField();
        txt_3 = new javax.swing.JTextField();
        txt_4 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JTextField();
        txt_6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("IP");

        btn_Tinh.setText("Tính");
        btn_Tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("/");

        jLabel3.setText("Địa chỉ IP Nhị Phân ");

        jLabel4.setText("Địa chỉ Mask");

        jLabel5.setText("Mask nhị phân");

        jLabel6.setText("Địa chỉ Network");

        jLabel7.setText("Network Nhị Phân");

        jLabel8.setText("Broadcast Nhị Phân");

        txt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Địa chỉ Broadcast");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_so1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_so2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_so3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_so4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_subnet, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Tinh))
                            .addComponent(txt_1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addComponent(txt_2)
                            .addComponent(txt_3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_7))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_so1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_so2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_so3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_so4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_subnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Tinh)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhActionPerformed
        // TODO add your handling code here:
        String ip1_so1 = String.valueOf(Integer.toBinaryString(Integer.parseInt(txt_so1.getText())));
        String ip1_so2 = String.valueOf(Integer.toBinaryString(Integer.parseInt(txt_so2.getText())));
        String ip1_so3 = String.valueOf(Integer.toBinaryString(Integer.parseInt(txt_so3.getText())));
        String ip1_so4 = String.valueOf(Integer.toBinaryString(Integer.parseInt(txt_so4.getText())));
        
        if(ip1_so1.length() < 8){
            String tmp = "";
            for (int i = 0; i < 8-ip1_so1.length(); i++) {
                tmp+="0";
            }
            tmp+=ip1_so1;
            ip1_so1 = tmp;
        }
        
        if(ip1_so2.length() < 8){
            String tmp = "";
            for (int i = 0; i < 8-ip1_so2.length(); i++) {
                tmp+="0";
            }
            tmp+=ip1_so2;
            ip1_so2 = tmp;
        }
        
        if(ip1_so3.length() < 8){
            String tmp = "";
            for (int i = 0; i < 8-ip1_so3.length(); i++) {
                tmp+="0";
            }
            tmp+=ip1_so3;
            ip1_so3 = tmp;
        }
        
        
        if(ip1_so4.length() < 8){
            String tmp = "";
            for (int i = 0; i < 8-ip1_so4.length(); i++) {
                tmp+="0";
            }
            tmp+=ip1_so4;
            ip1_so4 = tmp;
        }
        
        txt_1.setText(ip1_so1+"."+ip1_so2+"."+ip1_so3+"."+ip1_so4);
        
        //---------------------mask--------------------------------?
        
        String MaskNP ="";
        for (int i = 0; i < 32; i++) {
            if(i%8==0 && i != 0)
                MaskNP += ".";
            if(i < Integer.parseInt(txt_subnet.getText()))
                MaskNP+="1";
            else
                MaskNP+="0";
        }
        txt_3.setText(MaskNP);
        
        
        //---------------Subnet mask--------------------------------?
        
        String ip_sm[] = txt_3.getText().split("\\.");
        String MaskTP="";
        for (int i = 0; i < ip_sm.length; i++) {
            MaskTP += String.valueOf(Integer.parseInt(ip_sm[i], 2))+" ";
        }
        txt_2.setText(MaskTP.trim().replace(" ", "."));
        
        int subnet_ip = 32-Integer.parseInt(txt_subnet.getText());
        String tmp_ipv4 = txt_1.getText();
        tmp_ipv4 =tmp_ipv4.trim();
        
        String tmp_ipv4_1 = tmp_ipv4.substring(35-subnet_ip, tmp_ipv4.length());
        
        tmp_ipv4_1 = tmp_ipv4_1.replace("1", "0");
        
        tmp_ipv4 = txt_1.getText().substring(0, 35-subnet_ip)+tmp_ipv4_1;
        txt_4.setText(tmp_ipv4);
        
        //
        String val[] = txt_4.getText().split("\\.");
        String tmp_4 ="";
        for (String val1 : val) {
            tmp_4 += String.valueOf(Integer.parseInt(val1,2))+" ";
        }
        
        txt_5.setText(tmp_4.trim().replace(" ", "."));
        
        
        //-----------------------------------------------------------
            
        String invertedSubnetMask = "";
            for (int i = 0; i < 32; i++) {
        if (i % 8 == 0 && i != 0) {
            invertedSubnetMask += ".";
        }
        if (i < Integer.parseInt(txt_subnet.getText())) {
            invertedSubnetMask += "0"; // Invert: 1 becomes 0
        } else {
            invertedSubnetMask += "1"; // Invert: 0 becomes 1
        }
    }

    // Calculate the broadcast address
    String broadcastAddress = "";
    String[] ipParts = txt_1.getText().split("\\.");
    String[] invertedSubnetMaskParts = invertedSubnetMask.split("\\.");

    for (int i = 0; i < 4; i++) {
        int ipPart = Integer.parseInt(ipParts[i], 2);
        int invertedPart = Integer.parseInt(invertedSubnetMaskParts[i], 2);
        int broadcastPart = ipPart | invertedPart; // Bitwise OR operation
        broadcastAddress += String.format("%8s", Integer.toBinaryString(broadcastPart)).replace(' ', '0'); // Ensure 8 bits in each segment

        if (i < 3) {
            broadcastAddress += ".";
        }
    }

    // Display the binary broadcast address
    txt_7.setText(broadcastAddress);
        
    }//GEN-LAST:event_btn_TinhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B3_TH7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B3_TH7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B3_TH7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B3_TH7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B3_TH7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Tinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_6;
    private javax.swing.JTextField txt_7;
    private javax.swing.JTextField txt_so1;
    private javax.swing.JTextField txt_so2;
    private javax.swing.JTextField txt_so3;
    private javax.swing.JTextField txt_so4;
    private javax.swing.JTextField txt_subnet;
    // End of variables declaration//GEN-END:variables
}
